# 🧷 Generated by Faronix Manifest Engine
# Do not edit manually. Use .manifestrc and re-render.

{% for m in mounts %}
{{ m.source }} {{ m.target }} {{ m.type | default('none') }} {{ m.options | default('bind') }} 0 0
{% endfor %}
